# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: "Use .NET SDK 6.x"
  inputs:
    packageType: sdk
    version: '6.x'

- task: Npm@1
  displayName: "Run NPM install"
  inputs:
    verbose: false

- script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
  displayName: "Compile Sass Assets"

- task: gulp@1
  displayName: "Run Gulp Tasks"

- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildnfo.txt'
  displayName: "Write build info"
  workingDirectory: Tailspin.SpaceGame.Web/wwwroot

- task: DotNetCoreCLI@2
  displayName: "Restore Project Dependencies"
  inputs:
    command: "restore"
    projects: "**/*.csproj"

- task: DotNetCoreCLI@2
  displayName: "Build the project - Release" 
  inputs:
    command: "build"
    arguments: "--no-restore --configuration Release"
    projects: "**/*.csproj"